[build-system]
requires = ["maturin>=1.3.2"]
build-backend = "maturin"

[tool.maturin]
bindings = "pyo3"
features = ["extension-module"]
python-source = "python"
module-name = "chiklisp._chiklisp"

[project]
name = "chiklisp"
dynamic = ["version"]

# - Reenable these when we switch over from clvk_tools.
# [project.scripts]
# brun = "chiklisp.cmds:brun"
# run = "chiklisp.cmds:run"
# opc = "chiklisp.cmds:opc"
# opd = "chiklisp.cmds:opd"
# cldb = "chiklisp.cmds:cldb"
