name: npm publish

on:
  push:
    branches:
      - base1
  release:
    types: [published]
  pull_request:
    branches:
      - '**'

concurrency:
  # SHA is added to the end if on `main` to let all main workflows run
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ (github.ref == 'refs/heads/main') && github.sha || '' }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: write
  id-token: write

jobs:
  build_npm:
    name: Npm
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set Env
        uses: Chik-Network/actions/setjobenv@main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up rusts
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.97.1
          components: rustfmt, clippy

      - name: install wasm-pack
        run: cargo install --version 0.13.1 wasm-pack

      - name: wasm-pack build and pack
        run: |
          export RUSTFLAGS='--cfg=getrandom_backend="unsupported" -Ctarget-cpu=mvp'
          wasm-pack build --release --target=nodejs wasm && wasm-pack pack wasm

      - name: Setup Node 24.x
        uses: actions/setup-node@v6.3.0
        with:
          node-version: '24.x'

      # Cargo.toml won't allow an "@" in the name, so we just update the package name this way for NPM
      - name: Update package name for npm
        working-directory: ${{ github.workspace }}/wasm/pkg
        run: |
          cp package.json package.json.orig
          jq '.name="@chik-network/chiklisp"' package.json > temp.json && mv temp.json package.json

      - name: Test wasm
        run: node wasm/tests/index.js

      - name: Test clvk-js like wasm interface
        run: |
          cd wasm/tests/clvk-tools-interface && npm install && yarn test

      - name: Upload npm pkg artifacts
        uses: actions/upload-artifact@v7
        with:
          name: npm-pkg
          path: ./wasm/pkg/clvk_tools_wasm-*.tgz

      - name: Test for secrets access
        id: check_secrets
        shell: bash
        run: |
          unset HAS_SECRET
          if [ -n "$SECRET" ]; then HAS_SECRET='true' ; fi
          echo "HAS_SECRET=${HAS_SECRET}" >>$GITHUB_OUTPUT
        env:
          SECRET: "${{ secrets.NPM_TOKEN }}"

      - name: Ensure we have a new enough npm version for trusted publishing
        if: env.FULL_RELEASE == 'true'
        run: |
          npm install -g npm
          npm --version

      - name: Publish wasm
        if: env.FULL_RELEASE == 'true'
        working-directory: ${{ github.workspace }}/wasm/pkg
        run: |
          rm -f clvk_tools_wasm-*.tgz
          npm config set provenance true
          npm publish --access public
